parameters:
#    wotoog_user.example.class: Wotoog\UserBundle\Example\Twig_Extension

services:
#    wotoog_user.example:
#        class: %wotoog_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
