Wotoog\BlogBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: Wotoog\BlogBundle\Entity\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        visibility:
            type: string
            length: 10
            required: true
        title:
            type: string
            length: 64
            required: true
        createdAt:
            type: datetime
            column: created_at
            required: true
        updatedAt:
            type: datetime
            column: updated_at
            required: true
        content:
            type: text
            required: true
        description:
            type: string
            required: true
            lenght: 512
        category:
            type: string
            lenght: 32
        deleted:
            type: boolean
            column: deleted
    ManyToMany:
        tags:
            targetEntity: Tag
            joinTable:
                name: post_tag
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    manyToOne:
            blog:
                targetEntity: Blog
                inversedBy: posts
                joinColumn:
                    name: blog_id
                    referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [setDescription, setCreatedAtValue, setUpdatedAtValue]
        preUpdate: [setUpdatedAtValue]