wotoog_login:
    pattern:  /login
    defaults: { _controller: WotoogUserBundle:Security:login }

wotoog_register:
    pattern:  /register
    defaults: { _controller: WotoogUserBundle:Registration:register }