parameters:
#    wotoog_blog.example.class: Wotoog\BlogBundle\Example

services:
#    wotoog_blog.example:
#        class: %wotoog_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
