wotoog_feedback_page:
    pattern: /
    requirements: { _method: post }
    defaults: { _controller: WotoogCounterBundle:Default:sendMail}

wotoog_counter_homepage:
    pattern:  /
    defaults: { _controller: WotoogCounterBundle:Default:index }